package com.kyle.mybatis.bean;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_id
     *
     * @mbg.generated Sat May 04 12:50:53 CST 2019
     */
    private Integer newsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_themes
     *
     * @mbg.generated Sat May 04 12:50:53 CST 2019
     */
    private String newsThemes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_pictures
     *
     * @mbg.generated Sat May 04 12:50:53 CST 2019
     */
    private String newsPictures;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_id
     *
     * @return the value of news.news_id
     *
     * @mbg.generated Sat May 04 12:50:53 CST 2019
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_id
     *
     * @param newsId the value for news.news_id
     *
     * @mbg.generated Sat May 04 12:50:53 CST 2019
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_themes
     *
     * @return the value of news.news_themes
     *
     * @mbg.generated Sat May 04 12:50:53 CST 2019
     */
    public String getNewsThemes() {
        return newsThemes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_themes
     *
     * @param newsThemes the value for news.news_themes
     *
     * @mbg.generated Sat May 04 12:50:53 CST 2019
     */
    public void setNewsThemes(String newsThemes) {
        this.newsThemes = newsThemes == null ? null : newsThemes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_pictures
     *
     * @return the value of news.news_pictures
     *
     * @mbg.generated Sat May 04 12:50:53 CST 2019
     */
    public String getNewsPictures() {
        return newsPictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_pictures
     *
     * @param newsPictures the value for news.news_pictures
     *
     * @mbg.generated Sat May 04 12:50:53 CST 2019
     */
    public void setNewsPictures(String newsPictures) {
        this.newsPictures = newsPictures == null ? null : newsPictures.trim();
    }
}